language: cpp

compiler:
  - gcc

script: "nvcc -ccbin ~/gcc-4.4/ -lcuda -lcudart cuda_mandelbrot/mandelbrot.cu -L/usr/lib/nvidia-current/ -L/usr/lib/x86_64-linux-gnu/"

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq gcc-4.4
  - sudo apt-get install -qq nvidia-common
  - sudo apt-get install -qq nvidia-current
  - sudo apt-get install -qq nvidia-cuda-toolkit nvidia-cuda-dev
  - sudo apt-get install -qq libthrust-dev
  - sudo find /usr/ -name libcuda*.so
  - mkdir ~/gcc-4.4
  - cd ~/gcc-4.4 && ln -s /usr/bin/g++-4.4 g++ && ln -s /usr/bin/gcc-4.4 gcc && cd -
