language: cpp

compiler:
  - gcc

script:
  - alias nvcc="nvcc -ccbin ~/gcc-4.4/ -L/usr/lib/nvidia-current -L/usr/lib/x86_64-linux-gnu"
  - nvcc -lcuda -lcudart cuda_mandelbrot/mandelbrot.cu -o mandelbrot.o
  - nvcc -lcuda -lcudart thrust_sort/example.cu -o thrustsort.o

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq gcc-4.4
  - sudo apt-get install -qq nvidia-common
  - sudo apt-get install -qq nvidia-current
  - sudo apt-get install -qq nvidia-cuda-toolkit nvidia-cuda-dev
  - sudo apt-get install -qq libthrust-dev
  - sudo find /usr/ -name libcuda*.so
  - mkdir ~/gcc-4.4
  - cd ~/gcc-4.4 && ln -s /usr/bin/g++-4.4 g++ && ln -s /usr/bin/gcc-4.4 gcc && cd -

after_script:
  - ./mandelbrot.o
  - ./thrustsort.o > thrustsort.log
  - head -n 3 thrustsort.log
  - echo "..."
  - tail -n 3 thrustsort.log
